version: "3.8"
services:
  postgres:
    image: postgres:17
    container_name: postgres-GFI-LEOS
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    # command: bash -c "cd /var/lib/postgresql/data && mkdir pg_notify -p && mkdir pg_tblspc -p && mkdir pg_replslot -p && mkdir pg_twophase -p && mkdir pg_stat_tmp -p && mkdir pg_logical -p && mkdir pg_logical/snapshots -p && mkdir pg_logical/mappings -p && mkdir pg_commit_ts -p && mkdir pg_snapshot -p && docker-entrypoint.sh postgres"
    networks:
      - GFI-LEOS-network

networks:
  GFI-LEOS-network:
    driver: bridge